require 'rake'
require 'rake/testtask'

task :default => [:test_units]

desc "Run basic tests"
Rake::TestTask.new("test_units") do |t|
  t.test_files = Dir.glob("test/**/tc_*.rb")
  t.verbose = true
  t.warning = false
end
